<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<head>
    <title>Luvit documentation</title>
    <link rel="stylesheet" href="../ldoc.css" type="text/css" />
</head>
<body>

<div id="container">

<div id="product">
	<div id="product_logo"></div>
	<div id="product_name"><big><b></b></big></div>
	<div id="product_description"></div>
</div> <!-- id="product" -->


<div id="main">


<!-- Menu -->

<div id="navigation">
<br/>
<h1>Luvit</h1>

<ul>
  <li><a href="../index.html">Index</a></li>
</ul>



<h2>Topics</h2>
<ul>
  <li><a href="../topics/README.markdown.html">README.markdown</a></li>
  <li><a href="../topics/api.markdown.html">api.markdown</a></li>
  <li><a href="../topics/docs.markdown.html">docs.markdown</a></li>
  <li><strong>errors.markdown</strong></li>
</ul>
<h2>Modules</h2>
<ul>
  <li><a href="../modules/luvit.buffer.html">luvit.buffer</a></li>
  <li><a href="../modules/luvit.http.html">luvit.http</a></li>
  <li><a href="../modules/luvit.querystring.html">luvit.querystring</a></li>
  <li><a href="../modules/luvit.url.html">luvit.url</a></li>
</ul>
<h2>Examples</h2>
<ul>
  <li><a href="../examples/buffer-basics.lua.html">buffer-basics.lua</a></li>
  <li><a href="../examples/http-client.lua.html">http-client.lua</a></li>
  <li><a href="../examples/http-server.lua.html">http-server.lua</a></li>
</ul>

</div>

<div id="content">

<h1>Topic <code>errors.markdown</code></h1>



<h1>Classes of errors</h1>

<ul>
    <li>Sync argument errors.  These should "throw" and many do because that's how <code>luaL_check*</code> works.</li>
    <li>Errors while async.  These happened while trying to do an async action.  They should either be handed to the callback or emitted as error.</li>
    <li>Error while executing async callbacks.  If an error handler has a bug, there isn't much we can do.  Either "throw" or send as "error" event if possible.</li>
</ul>

<h1>Error handling</h1>

<ul>
    <li>async errors are always handed to lua somewhere with the exception of "error" events that aren't listened for</li>
    <li>uncaught "error" events and sync errors will crash the process and should always show a stack trace</li>
</ul>

<h1>Current places where async errors happen</h1>

<p>I know errno and path, this is a fs error</p>


<pre>
 luv_io_error(L, req-&gt;errorno, NULL, NULL, req-&gt;path);
</pre>

<p>I only know it was the last error (<code>after shutdown</code>, <code>after_write</code>, <code>on_connection</code>)</p>


<pre>
 luv_io_error(L, uv_last_error(uv_default_loop()).code, NULL, NULL, NULL);
</pre>



</div> <!-- id="content" -->
</div> <!-- id="main" -->
<div id="about">
<i>generated by <a href="http://github.com/stevedonovan/LDoc">LDoc 1.2</a></i>
</div> <!-- id="about" -->
</div> <!-- id="container" -->
</body>
</html>
